# write a python program to display IMDB's top rated 100 indian movies data(i.e.name,rating year of release)and make a DataFrame

In [1]:
# importing required libraries
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [2]:
url = "https://www.imdb.com/list/ls056092300/"

In [3]:
page = requests.get("https://www.imdb.com/list/ls056092300/")

In [4]:
page

In [18]:
soup = BeautifulSoup(page.content,"html.parser")

In [6]:
movie_name = []
year = []
rating = []

In [19]:
movie_data = soup.findAll('div',attrs={'class': "lister-item mode-detail" })

In [20]:
for store in movie_data:
    name = store.h3.a.text
    movie_name.append(name)

In [21]:
movie_name

['Ship of Theseus',
 'Iruvar',
 'Kaagaz Ke Phool',
 'Lagaan: Once Upon a Time in India',
 'Pather Panchali',
 'Charulata',
 'Rang De Basanti',
 'Dev.D',
 '3 Idiots',
 'Awaara',
 'Nayakan',
 'Aparajito',
 'Pushpaka Vimana',
 'Pyaasa',
 'Ghatashraddha',
 'Sholay',
 'Aradhana',
 'Do Ankhen Barah Haath',
 'Bombay',
 'Neecha Nagar',
 'Do Bigha Zamin',
 'Garm Hava',
 'Piravi',
 'Mughal-E-Azam',
 'Amma Ariyan',
 'Madhumati',
 'Goopy Gyne Bagha Byne',
 'Gangs of Wasseypur',
 'Guide',
 'Satya',
 'Roja',
 'Mr. India',
 'The Cloud-Capped Star',
 'Harishchandrachi Factory',
 'Masoom',
 'Agneepath',
 'Tabarana Kathe',
 'Zakhm',
 'رغبات القلب',
 'Bhaag Milkha Bhaag',
 'Chupke Chupke',
 'Dilwale Dulhania Le Jayenge',
 'Taare Zameen Par',
 'Ardh Satya',
 'Bhumika',
 'Enthiran',
 'Sadma',
 'Shwaas',
 'Lamhe',
 'Haqeeqat',
 'Shree 420',
 'Kannathil Muthamittal',
 'أنا لك!',
 'Ustad Hotel',
 'Bandit Queen',
 'Lakshya',
 'Black Friday',
 'Manthan',
 'Apoorva Raagangal',
 'English Vinglish',
 'Jewel Thief',
 'Pakeezah',
 'Maqbool',
 'Jis Desh Men Ganga Behti Hai',
 'Sahib Bibi Aur Ghulam',
 'Shatranj Ke Khilari',
 'Narthanasala',
 'Chandni Bar',
 'Vaaranam Aayiram',
 'Mr. and Mrs. Iyer',
 'Chandni',
 'English, August',
 'Celluloid',
 'Sagara Sangamam',
 'Munna Bhai M.B.B.S.',
 'Saaransh',
 'Guddi',
 'Vanaja',
 'Vazhakku Enn 18/9',
 'Gangaajal',
 'Angoor',
 'Guru',
 'Andaz Apna Apna',
 'Sangam',
 'Oka Oori Katha',
 'Bhuvan Shome',
 'Border',
 'Parineeta',
 'Devdas',
 'Abohomaan',
 'Kuch Kuch Hota Hai',
 'Pithamagan',
 'Veyyil',
 'Chemmeen',
 'Jaane Bhi Do Yaaro',
 'Apur Sansar',
 'Kanchivaram',
 'Monsoon Wedding',
 'Black',
 'Deewaar',
 'Ship of Theseus',
 'Iruvar',
 'Kaagaz Ke Phool',
 'Lagaan: Once Upon a Time in India',
 'Pather Panchali',
 'Charulata',
 'Rang De Basanti',
 'Dev.D',
 '3 Idiots',
 'Awaara',
 'Nayakan',
 'Aparajito',
 'Pushpaka Vimana',
 'Pyaasa',
 'Ghatashraddha',
 'Sholay',
 'Aradhana',
 'Do Ankhen Barah Haath',
 'Bombay',
 'Neecha Nagar',
 'Do Bigha Zamin',
 'Garm Hava',
 'Piravi',
 'Mughal-E-Azam',
 'Amma Ariyan',
 'Madhumati',
 'Goopy Gyne Bagha Byne',
 'Gangs of Wasseypur',
 'Guide',
 'Satya',
 'Roja',
 'Mr. India',
 'The Cloud-Capped Star',
 'Harishchandrachi Factory',
 'Masoom',
 'Agneepath',
 'Tabarana Kathe',
 'Zakhm',
 'رغبات القلب',
 'Bhaag Milkha Bhaag',
 'Chupke Chupke',
 'Dilwale Dulhania Le Jayenge',
 'Taare Zameen Par',
 'Ardh Satya',
 'Bhumika',
 'Enthiran',
 'Sadma',
 'Shwaas',
 'Lamhe',
 'Haqeeqat',
 'Shree 420',
 'Kannathil Muthamittal',
 'أنا لك!',
 'Ustad Hotel',
 'Bandit Queen',
 'Lakshya',
 'Black Friday',
 'Manthan',
 'Apoorva Raagangal',
 'English Vinglish',
 'Jewel Thief',
 'Pakeezah',
 'Maqbool',
 'Jis Desh Men Ganga Behti Hai',
 'Sahib Bibi Aur Ghulam',
 'Shatranj Ke Khilari',
 'Narthanasala',
 'Chandni Bar',
 'Vaaranam Aayiram',
 'Mr. and Mrs. Iyer',
 'Chandni',
 'English, August',
 'Celluloid',
 'Sagara Sangamam',
 'Munna Bhai M.B.B.S.',
 'Saaransh',
 'Guddi',
 'Vanaja',
 'Vazhakku Enn 18/9',
 'Gangaajal',
 'Angoor',
 'Guru',
 'Andaz Apna Apna',
 'Sangam',
 'Oka Oori Katha',
 'Bhuvan Shome',
 'Border',
 'Parineeta',
 'Devdas',
 'Abohomaan',
 'Kuch Kuch Hota Hai',
 'Pithamagan',
 'Veyyil',
 'Chemmeen',
 'Jaane Bhi Do Yaaro',
 'Apur Sansar',
 'Kanchivaram',
 'Monsoon Wedding',
 'Black',
 'Deewaar']

In [22]:
for store in movie_data:
    year_of_release = store.h3.find('span',class_="lister-item-year text-muted unbold").text.replace('(','').replace(')','')
    year.append(year_of_release)

In [23]:
year

['2012',
 '1997',
 '1959',
 '2001',
 '1955',
 '1964',
 '2006',
 '2009',
 '2009',
 '1951',
 '1987',
 '1956',
 '1987',
 '1957',
 '1977',
 '1975',
 '1969',
 '1957',
 '1995',
 '1946',
 '1953',
 '1974',
 '1989',
 '1960',
 '1986',
 '1958',
 '1969',
 '2012',
 '1965',
 '1998',
 '1992',
 '1987',
 '1960',
 '2009',
 '1983',
 '1990',
 '1986',
 '1998',
 '2001',
 '2013',
 '1975',
 '1995',
 '2007',
 '1983',
 '1977',
 '2010',
 '1983',
 '2004',
 '1991',
 '1964',
 '1955',
 '2002',
 '1994',
 '2012',
 '1994',
 '2004',
 '2004',
 '1976',
 '1975',
 '2012',
 '1967',
 '1972',
 '2003',
 '1960',
 '1962',
 '1977',
 '1963',
 '2001',
 '2008',
 '2002',
 '1989',
 '1994',
 '2013',
 '1983',
 '2003',
 '1984',
 '1971',
 '2006',
 '2012',
 '2003',
 '1982',
 '2007',
 '1994',
 'I 1964',
 '1978',
 '1969',
 'I 1997',
 '2005',
 '1955',
 '2009',
 '1998',
 '2003',
 '2006',
 '1965',
 '1983',
 '1959',
 '2008',
 '2001',
 '2005',
 '1975',
 '2012',
 '1997',
 '1959',
 '2001',
 '1955',
 '1964',
 '2006',
 '2009',
 '2009',
 '1951',
 '1987',
 '1956',
 '1987',
 '1957',
 '1977',
 '1975',
 '1969',
 '1957',
 '1995',
 '1946',
 '1953',
 '1974',
 '1989',
 '1960',
 '1986',
 '1958',
 '1969',
 '2012',
 '1965',
 '1998',
 '1992',
 '1987',
 '1960',
 '2009',
 '1983',
 '1990',
 '1986',
 '1998',
 '2001',
 '2013',
 '1975',
 '1995',
 '2007',
 '1983',
 '1977',
 '2010',
 '1983',
 '2004',
 '1991',
 '1964',
 '1955',
 '2002',
 '1994',
 '2012',
 '1994',
 '2004',
 '2004',
 '1976',
 '1975',
 '2012',
 '1967',
 '1972',
 '2003',
 '1960',
 '1962',
 '1977',
 '1963',
 '2001',
 '2008',
 '2002',
 '1989',
 '1994',
 '2013',
 '1983',
 '2003',
 '1984',
 '1971',
 '2006',
 '2012',
 '2003',
 '1982',
 '2007',
 '1994',
 'I 1964',
 '1978',
 '1969',
 'I 1997',
 '2005',
 '1955',
 '2009',
 '1998',
 '2003',
 '2006',
 '1965',
 '1983',
 '1959',
 '2008',
 '2001',
 '2005',
 '1975']

In [24]:
for store in movie_data:
    rate = store.find('span',class_="ipl-rating-star__rating").text.replace('\n','')
    rating.append(rate)

In [14]:
rating

['8',
 '8.5',
 '7.8',
 '8.1',
 '8.3',
 '8.1',
 '8.1',
 '8',
 '8.5',
 '7.8',
 '8.7',
 '8.3',
 '8.6',
 '8.3',
 '7.6',
 '8.1',
 '7.6',
 '8.4',
 '8.1',
 '6.8',
 '8.2',
 '8.1',
 '7.8',
 '8.2',
 '7.1',
 '7.8',
 '8.7',
 '8.2',
 '8.4',
 '8.3',
 '8.2',
 '7.8',
 '7.9',
 '8.4',
 '8.4',
 '7.6',
 '7.9',
 '7.9',
 '8.1',
 '8.3',
 '8.3',
 '8.1',
 '8.4',
 '8.1',
 '7.4',
 '7.1',
 '8.3',
 '8.2',
 '7.3',
 '7.9',
 '7.9',
 '8.4',
 '7.5',
 '8.3',
 '7.5',
 '7.9',
 '8.5',
 '7.6',
 '7.6',
 '7.9',
 '7.9',
 '7.2',
 '8.1',
 '7.1',
 '8.1',
 '7.5',
 '8.1',
 '7.6',
 '8.4',
 '7.9',
 '6.7',
 '7.6',
 '7.8',
 '8.9',
 '8.1',
 '8.1',
 '7.2',
 '7.2',
 '8.3',
 '7.8',
 '8.3',
 '7.7',
 '8.1',
 '7.3',
 '7.7',
 '7.3',
 '8',
 '7.2',
 '7.7',
 '7.4',
 '7.7',
 '8.4',
 '7.8',
 '7.8',
 '8.4',
 '8.5',
 '8.1',
 '7.3',
 '8.2',
 '8']

In [15]:
movie_DF = pd.DataFrame({'Name of movie': movie_name,'Year of release': year, 'Movie Rating': rating})

In [16]:
movie_DF

                        Name of movie Year of release Movie Rating
0                     Ship of Theseus            2012            8
1                              Iruvar            1997          8.5
2                     Kaagaz Ke Phool            1959          7.8
3   Lagaan: Once Upon a Time in India            2001          8.1
4                     Pather Panchali            1955          8.3
..                                ...             ...          ...
95                        Apur Sansar            1959          8.5
96                        Kanchivaram            2008          8.1
97                    Monsoon Wedding            2001          7.3
98                              Black            2005          8.2
99                            Deewaar            1975            8

[100 rows x 3 columns]

In [17]:
movie_DF.to_csv('IMDB Top Indian Movies.csv', index=False)