# write a python program to display IMDB'S toprated 100 movie's data (i.e. name,rating,year of release) and make a DataFrame

In [1]:
# importing the required libraries
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [2]:
url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

In [3]:
page = requests.get('https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc')

In [4]:
page

In [6]:
soup = BeautifulSoup(page.content,"html.parser")

In [7]:
movie_name = []
year = []
rating = []

In [8]:
movie_data = soup.findAll('div',attrs={'class': "lister-item mode-advanced"})

In [9]:
for store in movie_data:
    name = store.h3.a.text
    movie_name.append(name)

In [10]:
movie_name

['The Shawshank Redemption',
 'The Godfather',
 'The Dark Knight',
 'The Lord of the Rings: The Return of the King',
 "Schindler's List",
 'The Godfather: Part II',
 '12 Angry Men',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Pulp Fiction',
 'Inception',
 'The Lord of the Rings: The Two Towers',
 'Fight Club',
 'Forrest Gump',
 'Il buono, il brutto, il cattivo',
 'Interstellar',
 'The Matrix',
 'Goodfellas',
 'Star Wars: Episode V - The Empire Strikes Back',
 "One Flew Over the Cuckoo's Nest",
 'Seven Samurai',
 "It's a Wonderful Life",
 'Cidade de Deus',
 'The Pianist',
 'Spirited Away',
 'Saving Private Ryan',
 'The Green Mile',
 'La vita è bella',
 'Se7en',
 'Léon',
 'Terminator 2: Judgment Day',
 'The Silence of the Lambs',
 'Back to the Future',
 'Star Wars',
 'Hara-Kiri',
 'Gisaengchung',
 'Avengers: Infinity War',
 'Whiplash',
 'Django Unchained',
 'Intouchables',
 '3 Idiots',
 'Spider-Man: No Way Home',
 'The Prestige',
 'The Departed',
 'Memento',
 'Gladiator',
 'American History X',
 'The Usual Suspects',
 'The Lion King',
 'Cinema Paradiso',
 'Hotaru no haka']

In [11]:
for store in movie_data:
    year_of_release = store.h3.find('span',class_="lister-item-year text-muted unbold").text.replace('(','').replace(')','')
    year.append(year_of_release)

In [12]:
year

['1994',
 '1972',
 '2008',
 '2003',
 '1993',
 '1974',
 '1957',
 '2001',
 '1994',
 '2010',
 '2002',
 '1999',
 '1994',
 '1966',
 '2014',
 '1999',
 '1990',
 '1980',
 '1975',
 '1954',
 '1946',
 '2002',
 '2002',
 '2001',
 '1998',
 '1999',
 '1997',
 '1995',
 '1994',
 '1991',
 '1991',
 '1985',
 '1977',
 '1962',
 '2019',
 '2018',
 '2014',
 '2012',
 '2011',
 '2009',
 '2021',
 '2006',
 '2006',
 '2000',
 '2000',
 '1998',
 '1995',
 '1994',
 '1988',
 '1988']

In [13]:
for store in movie_data:
    rate = store.find('div',class_="inline-block ratings-imdb-rating").text.replace('\n','')
    rating.append(rate)

In [14]:
rating

['9.3',
 '9.2',
 '9.1',
 '9.0',
 '9.0',
 '9.0',
 '9.0',
 '8.9',
 '8.9',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5']

In [15]:
np.count_nonzero(rating)

50

In [16]:
movie_DF = pd.DataFrame({'Name of movie': movie_name, 'Year of release': year, 'Movie Rating': rating })

In [17]:
movie_DF

,Name of movie,Year of release,Movie Rating
0,The Shawshank Redemption,1994,9.3
1,The Godfather,1972,9.2
2,The Dark Knight,2008,9.1
3,The Lord of the Rings: The Return of the King,2003,9.0
4,Schindler's List,1993,9.0
5,The Godfather: Part II,1974,9.0
6,12 Angry Men,1957,9.0
7,The Lord of the Rings: The Fellowship of the Ring,2001,8.9
8,Pulp Fiction,1994,8.9
9,Inception,2010,8.8
10,The Lord of the Rings: The Two Towers,2002,8.8
11,Fight Club,1999,8.8
12,Forrest Gump,1994,8.8
13,"Il buono, il brutto, il cattivo",1966,8.8
14,Interstellar,2014,8.7
15,The Matrix,1999,8.7
16,Goodfellas,1990,8.7
17,Star Wars: Episode V - The Empire Strikes Back,1980,8.7
18,One Flew Over the Cuckoo's Nest,1975,8.7
19,Seven Samurai,1954,8.7
20,It's a Wonderful Life,1946,8.7
21,Cidade de Deus,2002,8.6
22,The Pianist,2002,8.6
23,Spirited Away,2001,8.6
24,Saving Private Ryan,1998,8.6
25,The Green Mile,1999,8.6
26,La vita è bella,1997,8.6
27,Se7en,1995,8.6
28,Léon,1994,8.6
29,Terminator 2: Judgment Day,1991,8.6
30,The Silence of the Lambs,1991,8.6
31,Back to the Future,1985,8.6
32,Star Wars,1977,8.6
33,Hara-Kiri,1962,8.6
34,Gisaengchung,2019,8.5
35,Avengers: Infinity War,2018,8.5
36,Whiplash,2014,8.5
37,Django Unchained,2012,8.5
38,Intouchables,2011,8.5
39,3 Idiots,2009,8.5
40,Spider-Man: No Way Home,2021,8.5
41,The Prestige,2006,8.5
42,The Departed,2006,8.5
43,Memento,2000,8.5
44,Gladiator,2000,8.5
45,American History X,1998,8.5
46,The Usual Suspects,1995,8.5
47,The Lion King,1994,8.5
48,Cinema Paradiso,1988,8.5
49,Hotaru no haka,1988,8.5

In [37]:
movie_DF.to_csv('IMDB Top Movies.csv', index=False)